Repository KAIST-CS408E/WebSpector, pull requests merged in 2018-10, with the labels that each got.

#1 Instrument
  app/__init__.py
  app/instrument/__init__.py
  app/instrument/prev_instrument.js
  app/instrument/reproducer.py
  app/proxy/LICENSE
  app/proxy/__init__.py
  app/proxy/proxy.py
  app/proxy/proxy_util.py
  app/proxy/setup_https_intercept.sh
Labels: enhancement

#7 Add docker-compose.yml
  .gitignore
  backend/docker-compose.yml
  backend/proxy_worker.Dockerfile
  backend/webapp.Dockerfile
Labels: enhancement

#9 Support HTTPS proxy
  app/proxy/proxy_util.py
Labels: bug

#10 Implemented HTTP proxy worker
  .gitignore
  backend/docker-compose.yml
  backend/proxy_worker.Dockerfile
  backend/proxy_worker/main.py
  backend/proxy_worker/requirements.txt
Labels: enhancement

#14 Support HTTPS server and Add RootCA certificate file and key file
  .gitignore
  backend/proxy_worker/cert/gen_sslcrt.sh
  backend/proxy_worker/cert/host.conf
  backend/proxy_worker/main.py
  cert/gen_rootCA.sh
  cert/rootCA.conf
  cert/rootCA.crt
  cert/rootCA.csr
  cert/rootCA.srl
  cert/rootCAkey.pem
Labels: bug, enhancement

#16 Fix bugs when JSON data are inserted into DB
  backend/proxy_worker/main.py
Labels: bug
